#!/bin/bash

cd ${DEV_ROOT}/my-bash/xg279q-control || exit $?

if [[ ! -d .venv ]]; then
  python -m venv .venv || exit $?
  source .venv/bin/activate || exit $?
  pip install monitorcontrol || exit $?
fi